hy:
  file:
    source:
      #path: C:/code/\u957F\u6C99\u7ECF\u5F00\u533A\u4EA7\u4E1A\u94FE\u4F9B\u9700\u96C6\u5E02/\u540E\u7AEF/jkqcyl
      path: C:\\code\\\u957F\u6C99\u7ECF\u5F00\u533A\u4EA7\u4E1A\u94FE\u4F9B\u9700\u96C6\u5E02\\\u540E\u7AEF\\jkqcyl
    target:
      path: C:\\code
